// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAIgdkcPvrHbIlH6Nqg1ja_l4PlKO4obw',
    appId: '1:556871484758:android:cfcd19bdba922cd2f482f7',
    messagingSenderId: '556871484758',
    projectId: 'authexample1-5ce43',
    storageBucket: 'authexample1-5ce43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZd6BYnmjx9QGwErLAPdi6yfZm4-4JpAw',
    appId: '1:556871484758:ios:01e73fc4273026f0f482f7',
    messagingSenderId: '556871484758',
    projectId: 'authexample1-5ce43',
    storageBucket: 'authexample1-5ce43.firebasestorage.app',
    iosClientId: '556871484758-rpropkfqarjk4i8t4a53m2uom6qdheba.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX203kK-16CvJYWpps0zQ8BIuF5VhBAN8',
    appId: '1:556871484758:web:9b2b2523dcc49fc8f482f7',
    messagingSenderId: '556871484758',
    projectId: 'authexample1-5ce43',
    authDomain: 'authexample1-5ce43.firebaseapp.com',
    storageBucket: 'authexample1-5ce43.firebasestorage.app',
    measurementId: 'G-0030YGQFVB',
  );

}